#pragma once

#include "sdkconfig.h"

// Map Kconfig values to standard Profile constants

#define FLXOS_DISPLAY_WIDTH CONFIG_FLXOS_DISPLAY_WIDTH
#define FLXOS_DISPLAY_HEIGHT CONFIG_FLXOS_DISPLAY_HEIGHT
#define FLXOS_DISPLAY_ROTATION CONFIG_FLXOS_DISPLAY_ROTATION_VALUE

// Display Panel Settings
#define FLXOS_PANEL_OFFSET_X CONFIG_FLXOS_PANEL_OFFSET_X
#define FLXOS_PANEL_OFFSET_Y CONFIG_FLXOS_PANEL_OFFSET_Y
#define FLXOS_PANEL_OFFSET_ROTATION CONFIG_FLXOS_PANEL_OFFSET_ROTATION
#define FLXOS_DUMMY_READ_PIXEL CONFIG_FLXOS_DUMMY_READ_PIXEL
#define FLXOS_DUMMY_READ_BITS CONFIG_FLXOS_DUMMY_READ_BITS
#define FLXOS_PANEL_READABLE CONFIG_FLXOS_PANEL_READABLE
#define FLXOS_PANEL_DLEN_16BIT CONFIG_FLXOS_PANEL_DLEN_16BIT
#define FLXOS_BUS_SHARED CONFIG_FLXOS_BUS_SHARED
#define FLXOS_DISPLAY_INVERT CONFIG_FLXOS_DISPLAY_INVERT
#define FLXOS_DISPLAY_RGB_ORDER CONFIG_FLXOS_DISPLAY_RGB_ORDER

// Display Bus Settings (SPI)
#if CONFIG_FLXOS_SPI_HOST == 1
#define FLXOS_SPI_HOST SPI2_HOST
#elif CONFIG_FLXOS_SPI_HOST == 2
#define FLXOS_SPI_HOST SPI3_HOST
#else
#define FLXOS_SPI_HOST SPI2_HOST
#endif
#define FLXOS_SPI_MODE CONFIG_FLXOS_SPI_MODE
#define FLXOS_SPI_FREQ_WRITE CONFIG_FLXOS_SPI_FREQ_WRITE
#define FLXOS_SPI_FREQ_READ CONFIG_FLXOS_SPI_FREQ_READ
#define FLXOS_SPI_3WIRE CONFIG_FLXOS_SPI_3WIRE
#define FLXOS_SPI_DMA_CHANNEL CONFIG_FLXOS_SPI_DMA_CHANNEL

// Display Pins
#define FLXOS_PIN_CS CONFIG_FLXOS_PIN_CS
#define FLXOS_PIN_DC CONFIG_FLXOS_SPI_PIN_DC
#define FLXOS_PIN_RST CONFIG_FLXOS_PIN_RST
#define FLXOS_PIN_BUSY CONFIG_FLXOS_PIN_BUSY
#define FLXOS_PIN_BCKL CONFIG_FLXOS_PIN_BCKL
#define FLXOS_PIN_MOSI CONFIG_FLXOS_PIN_MOSI
#define FLXOS_PIN_SCLK CONFIG_FLXOS_PIN_SCLK
#define FLXOS_PIN_MISO CONFIG_FLXOS_PIN_MISO

// Backlight Settings
#define FLXOS_BCKL_INVERT CONFIG_FLXOS_BCKL_INVERT
#define FLXOS_BCKL_FREQ CONFIG_FLXOS_BCKL_FREQ
#define FLXOS_BCKL_PWM_CHANNEL CONFIG_FLXOS_BCKL_PWM_CHANNEL

// Touch Configuration
#if CONFIG_FLXOS_TOUCH_ENABLED
#define FLXOS_TOUCH_ENABLED true
#define FLXOS_PIN_TOUCH_CS CONFIG_FLXOS_PIN_TOUCH_CS
#define FLXOS_PIN_TOUCH_INT CONFIG_FLXOS_PIN_TOUCH_INT
#define FLXOS_TOUCH_SPI_FREQ CONFIG_FLXOS_TOUCH_SPI_FREQ
#define FLXOS_TOUCH_BUS_SHARED CONFIG_FLXOS_TOUCH_BUS_SHARED
#define FLXOS_TOUCH_SPI_SEPARATE_PINS CONFIG_FLXOS_TOUCH_SPI_SEPARATE_PINS
#if CONFIG_FLXOS_TOUCH_SPI_HOST == 1
#define FLXOS_TOUCH_SPI_HOST SPI2_HOST
#elif CONFIG_FLXOS_TOUCH_SPI_HOST == 2
#define FLXOS_TOUCH_SPI_HOST SPI3_HOST
#else
#define FLXOS_TOUCH_SPI_HOST -1
#endif
#define FLXOS_PIN_TOUCH_SCLK CONFIG_FLXOS_PIN_TOUCH_SCLK
#define FLXOS_PIN_TOUCH_MOSI CONFIG_FLXOS_PIN_TOUCH_MOSI
#define FLXOS_PIN_TOUCH_MISO CONFIG_FLXOS_PIN_TOUCH_MISO

// Touch Calibration
#define FLXOS_TOUCH_X_MIN CONFIG_FLXOS_TOUCH_X_MIN
#define FLXOS_TOUCH_X_MAX CONFIG_FLXOS_TOUCH_X_MAX
#define FLXOS_TOUCH_Y_MIN CONFIG_FLXOS_TOUCH_Y_MIN
#define FLXOS_TOUCH_Y_MAX CONFIG_FLXOS_TOUCH_Y_MAX
#define FLXOS_TOUCH_OFFSET_ROTATION CONFIG_FLXOS_TOUCH_OFFSET_ROTATION
#else
#define FLXOS_TOUCH_ENABLED false
#define FLXOS_PIN_TOUCH_CS -1
#define FLXOS_PIN_TOUCH_INT -1
#define FLXOS_TOUCH_SPI_FREQ 0
#define FLXOS_TOUCH_BUS_SHARED false
#define FLXOS_TOUCH_SPI_SEPARATE_PINS false
#define FLXOS_TOUCH_SPI_HOST -1
#define FLXOS_PIN_TOUCH_SCLK -1
#define FLXOS_PIN_TOUCH_MOSI -1
#define FLXOS_PIN_TOUCH_MISO -1
#define FLXOS_TOUCH_X_MIN 0
#define FLXOS_TOUCH_X_MAX 0
#define FLXOS_TOUCH_Y_MIN 0
#define FLXOS_TOUCH_Y_MAX 0
#define FLXOS_TOUCH_OFFSET_ROTATION 0
#endif

// SD Card Configuration
#if CONFIG_FLXOS_SD_CARD_ENABLED
#define FLXOS_SD_CARD_ENABLED true
#define FLXOS_SD_CS CONFIG_FLXOS_SD_PIN_CS
#define FLXOS_SD_MOUNT_POINT CONFIG_FLXOS_SD_MOUNT_POINT
#if CONFIG_FLXOS_SD_SPI_HOST == 1
#define FLXOS_SD_SPI_HOST SPI2_HOST
#elif CONFIG_FLXOS_SD_SPI_HOST == 2
#define FLXOS_SD_SPI_HOST SPI3_HOST
#else
#define FLXOS_SD_SPI_HOST SPI2_HOST
#endif
#define FLXOS_SD_MAX_FREQ_KHZ CONFIG_FLXOS_SD_MAX_FREQ_KHZ
#define FLXOS_SD_PIN_MOSI CONFIG_FLXOS_SD_PIN_MOSI
#define FLXOS_SD_PIN_MISO CONFIG_FLXOS_SD_PIN_MISO
#define FLXOS_SD_PIN_SCLK CONFIG_FLXOS_SD_PIN_SCLK
#else
#define FLXOS_SD_CARD_ENABLED false
#endif
