// Generated by Buildscripts/hwgen.py
// Profile: generic-esp32s3
// Source: Profiles/generic-esp32s3/profile.yaml (derived)
// Generated: 2026-02-23T15:01:52Z
//
// This file is an initialization scaffold. Fill in TODO blocks with
// concrete driver creation and registration for the profile.

#include <array>
#include <esp_err.h>

namespace flx::profile::generic_esp32s3::hwd {

namespace {

struct BusDescriptor {
    const char* name;
    const char* type;
    const char* controller;
};

struct PeripheralDescriptor {
    const char* name;
    const char* type;
    const char* bus;
};

constexpr std::array<BusDescriptor, 1> kBuses = {{
    BusDescriptor{"usb_serial_jtag0", "usb_serial_jtag", "USB_SERIAL_JTAG"},
}};

constexpr std::array<PeripheralDescriptor, 1> kPeripherals = {{
    PeripheralDescriptor{"cli_console", "cli", "usb_serial_jtag0"},
}};
}  // namespace

void initBuses() {
    for (const auto& bus : kBuses) {
        // TODO: Configure and initialize this bus.
    }

    // Bus topology derived from profile metadata:
    // - usb_serial_jtag0: port=USB_SERIAL_JTAG, type=usb_serial_jtag
}

void initPeripherals() {
    for (const auto& peripheral : kPeripherals) {
        // TODO: Instantiate and wire this peripheral.
    }

    // Peripheral topology derived from profile metadata:
    // - cli_console: bus=usb_serial_jtag0, prompt=flxos> , type=cli
}

void initHardware() {
    initBuses();
    initPeripherals();
}

}  // namespace flx::profile::generic_esp32s3::hwd

extern "C" esp_err_t flx_profile_hwd_init() {
    flx::profile::generic_esp32s3::hwd::initHardware();
    return ESP_OK;
}
