// Generated by Buildscripts/hwgen.py
// Profile: lilygo-t-hmi
// Source: Profiles/lilygo-t-hmi/profile.yaml (derived)
// Generated: 2026-03-08T06:52:35Z
//
// This file is an initialization scaffold. Fill in TODO blocks with
// concrete driver creation and registration for the profile.

#include <array>
#include <driver/gpio.h>
#include <esp_err.h>

#include <flx/hal/DeviceRegistry.hpp>
#include <flx/hal/display/LgfxDisplayDevice.hpp>
#include <flx/hal/touch/LgfxTouchDevice.hpp>
#include <flx/hal/sdcard/SpiSdCardDevice.hpp>
#include <flx/hal/spi/EspSpiBus.hpp>
#include <flx/hal/i2c/EspI2cBus.hpp>

namespace flx::profile::lilygo_t_hmi::hwd {

namespace {

struct BusDescriptor {
    const char* name;
    const char* type;
    const char* controller;
};

struct PeripheralDescriptor {
    const char* name;
    const char* type;
    const char* bus;
};

constexpr std::array<BusDescriptor, 2> kBuses = {{
    BusDescriptor{"spi_touch", "spi", "SPI2_HOST"},
    BusDescriptor{"usb_serial_jtag0", "usb_serial_jtag", "USB_SERIAL_JTAG"},
}};

constexpr std::array<PeripheralDescriptor, 3> kPeripherals = {{
    PeripheralDescriptor{"board_power", "gpio_power", ""},
    PeripheralDescriptor{"cli_console", "cli", "usb_serial_jtag0"},
    PeripheralDescriptor{"touch", "touch", "spi_touch"},
}};
}  // namespace

constexpr std::array<int, 2> kBoardPowerOnPins = {{14, 10}};
constexpr int kBoardPowerOnLevel = 1;

esp_err_t initBoardPowerPins() {
    gpio_config_t cfg = {};
    cfg.mode = GPIO_MODE_OUTPUT;
    cfg.pull_up_en = GPIO_PULLUP_DISABLE;
    cfg.pull_down_en = GPIO_PULLDOWN_DISABLE;
    cfg.intr_type = GPIO_INTR_DISABLE;
    for (int pin_value : kBoardPowerOnPins) {
        const gpio_num_t pin = static_cast<gpio_num_t>(pin_value);
        cfg.pin_bit_mask = 1ULL << pin;
        const esp_err_t cfg_err = gpio_config(&cfg);
        if (cfg_err != ESP_OK) {
            return cfg_err;
        }
        const esp_err_t set_err = gpio_set_level(pin, kBoardPowerOnLevel);
        if (set_err != ESP_OK) {
            return set_err;
        }
    }
    return ESP_OK;
}

void initHardware() {
    auto& registry = flx::hal::DeviceRegistry::getInstance();

    // Autogenerated functional instantiation:
    registry.registerDevice(std::make_shared<flx::hal::spi::EspSpiBus>(SPI2_HOST, -1, -1, -1));
    {
        auto display = registry.findFirst<flx::hal::display::IDisplayDevice>(flx::hal::IDevice::Type::Display);
        if (display) {
            auto* lgfx_disp = std::static_pointer_cast<flx::hal::display::LgfxDisplayDevice>(display).get();
            if (lgfx_disp) {
                auto touch = std::make_shared<flx::hal::touch::LgfxTouchDevice>(lgfx_disp->getRawDriver());
                if (touch->start()) registry.registerDevice(touch);
            }
        }
    }
}

}  // namespace flx::profile::lilygo_t_hmi::hwd

extern "C" esp_err_t flx_profile_hwd_init() {
    const esp_err_t power_err = flx::profile::lilygo_t_hmi::hwd::initBoardPowerPins();
    if (power_err != ESP_OK) {
        return power_err;
    }
    flx::profile::lilygo_t_hmi::hwd::initHardware();
    return ESP_OK;
}
