// Generated by Buildscripts/hwgen.py
// Profile: lilygo-t-hmi
// Source: Profiles/lilygo-t-hmi/profile.yaml (derived)
// Generated: 2026-02-23T15:01:52Z
//
// This file is an initialization scaffold. Fill in TODO blocks with
// concrete driver creation and registration for the profile.

#include <array>
#include <driver/gpio.h>
#include <esp_err.h>

namespace flx::profile::lilygo_t_hmi::hwd {

namespace {

struct BusDescriptor {
    const char* name;
    const char* type;
    const char* controller;
};

struct PeripheralDescriptor {
    const char* name;
    const char* type;
    const char* bus;
};

constexpr std::array<BusDescriptor, 2> kBuses = {{
    BusDescriptor{"spi_touch", "spi", "SPI2_HOST"},
    BusDescriptor{"usb_serial_jtag0", "usb_serial_jtag", "USB_SERIAL_JTAG"},
}};

constexpr std::array<PeripheralDescriptor, 3> kPeripherals = {{
    PeripheralDescriptor{"board_power", "gpio_power", ""},
    PeripheralDescriptor{"cli_console", "cli", "usb_serial_jtag0"},
    PeripheralDescriptor{"touch", "touch", "spi_touch"},
}};
}  // namespace

constexpr std::array<int, 2> kBoardPowerOnPins = {{14, 10}};
constexpr int kBoardPowerOnLevel = 1;

esp_err_t initBoardPowerPins() {
    gpio_config_t cfg = {};
    cfg.mode = GPIO_MODE_OUTPUT;
    cfg.pull_up_en = GPIO_PULLUP_DISABLE;
    cfg.pull_down_en = GPIO_PULLDOWN_DISABLE;
    cfg.intr_type = GPIO_INTR_DISABLE;
    for (int pin_value : kBoardPowerOnPins) {
        const gpio_num_t pin = static_cast<gpio_num_t>(pin_value);
        cfg.pin_bit_mask = 1ULL << pin;
        const esp_err_t cfg_err = gpio_config(&cfg);
        if (cfg_err != ESP_OK) {
            return cfg_err;
        }
        const esp_err_t set_err = gpio_set_level(pin, kBoardPowerOnLevel);
        if (set_err != ESP_OK) {
            return set_err;
        }
    }
    return ESP_OK;
}

void initBuses() {
    for (const auto& bus : kBuses) {
        // TODO: Configure and initialize this bus.
    }

    // Bus topology derived from profile metadata:
    // - spi_touch: freq_hz=1000000, host=SPI2_HOST, mode=0, pins.miso=4, pins.mosi=3, pins.sclk=1, type=spi
    // - usb_serial_jtag0: port=USB_SERIAL_JTAG, type=usb_serial_jtag
}

void initPeripherals() {
    for (const auto& peripheral : kPeripherals) {
        // TODO: Instantiate and wire this peripheral.
    }

    // Peripheral topology derived from profile metadata:
    // - board_power: on_level=1, pins=[14, 10], type=gpio_power
    // - cli_console: bus=usb_serial_jtag0, prompt=flxos> , type=cli
    // - touch: bus=spi_touch, calibration.offset_rotation=0, calibration.x_max=3800, calibration.x_min=200, calibration.y_max=3800, calibration.y_min=200, driver=XPT2046, pins.cs=2, pins.int=9, type=touch
}

void initHardware() {
    initBuses();
    initPeripherals();
}

}  // namespace flx::profile::lilygo_t_hmi::hwd

extern "C" esp_err_t flx_profile_hwd_init() {
    const esp_err_t power_err = flx::profile::lilygo_t_hmi::hwd::initBoardPowerPins();
    if (power_err != ESP_OK) {
        return power_err;
    }
    flx::profile::lilygo_t_hmi::hwd::initHardware();
    return ESP_OK;
}
