#!/bin/bash
# Run FlxOS premium-readiness baseline checks and generate a dated report.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
DATE_TAG="$(date +%Y-%m-%d)"
TIME_TAG="$(date +%H:%M:%S)"
OUT_DIR="$PROJECT_ROOT/reports/premium_readiness/$DATE_TAG"
REPORT_FILE="$OUT_DIR/premium_baseline_report.md"

mkdir -p "$OUT_DIR"

CHECK_IDS=("format" "naming" "docs" "includes" "complexity")
CHECK_NAMES=(
    "Format Check"
    "Naming Check"
    "Documentation Check"
    "Include Analysis"
    "Complexity Analysis"
)
CHECK_CMDS=(
    "bash $SCRIPT_DIR/check_format.sh"
    "python3 $SCRIPT_DIR/check_naming.py"
    "python3 $SCRIPT_DIR/check_docs.py"
    "python3 $SCRIPT_DIR/analyze_includes.py"
    "python3 $SCRIPT_DIR/analyze_complexity.py"
)

PASS_COUNT=0
FAIL_COUNT=0
TOTAL_ISSUES=0

extract_issue_count() {
    local check_id="$1"
    local log_file="$2"

    case "$check_id" in
        format)
            grep -c "Needs formatting" "$log_file" || true
            ;;
        naming)
            awk '/Issues found:/{value=$3} END{if (value == "") value=0; print value}' "$log_file"
            ;;
        docs)
            awk '
                /Files without headers:/{headers=$4}
                /Undocumented functions:/{undoc=$3}
                /Missing READMEs:/{readmes=$3}
                END{
                    if (headers == "") headers=0;
                    if (undoc == "") undoc=0;
                    if (readmes == "") readmes=0;
                    print headers + undoc + readmes;
                }
            ' "$log_file"
            ;;
        includes)
            awk '/Total issues:/{value=$3} END{if (value == "") value=0; print value}' "$log_file"
            ;;
        complexity)
            awk '/Issues found:/{value=$3} END{if (value == "") value=0; print value}' "$log_file"
            ;;
        *)
            echo "0"
            ;;
    esac
}

extract_signal_line() {
    local log_file="$1"
    local signal
    signal="$(grep -m1 -E "❌|⚠️|error|warning" "$log_file" || true)"
    if [[ -z "$signal" ]]; then
        signal="No explicit warning line found"
    fi
    echo "$signal"
}

declare -a RESULT_STATUS
declare -a RESULT_EXIT
declare -a RESULT_ISSUES
declare -a RESULT_SIGNAL
declare -a RESULT_LOG_REL

echo "Running premium baseline checks..."
echo "Output directory: $OUT_DIR"

for i in "${!CHECK_IDS[@]}"; do
    check_id="${CHECK_IDS[$i]}"
    check_name="${CHECK_NAMES[$i]}"
    check_cmd="${CHECK_CMDS[$i]}"
    log_file="$OUT_DIR/${check_id}.log"

    echo "- $check_name"

    set +e
    eval "$check_cmd" > "$log_file" 2>&1
    exit_code=$?
    set -e

    issues="$(extract_issue_count "$check_id" "$log_file")"
    signal_line="$(extract_signal_line "$log_file")"

    if [[ "$exit_code" -eq 0 ]]; then
        status="PASS"
        PASS_COUNT=$((PASS_COUNT + 1))
    else
        status="FAIL"
        FAIL_COUNT=$((FAIL_COUNT + 1))
    fi

    TOTAL_ISSUES=$((TOTAL_ISSUES + issues))
    RESULT_STATUS[$i]="$status"
    RESULT_EXIT[$i]="$exit_code"
    RESULT_ISSUES[$i]="$issues"
    RESULT_SIGNAL[$i]="$signal_line"
    RESULT_LOG_REL[$i]="reports/premium_readiness/$DATE_TAG/${check_id}.log"
done

QUALITY_SCORE=$((PASS_COUNT * 100 / ${#CHECK_IDS[@]}))

{
    echo "# FlxOS Premium Baseline Report"
    echo
    echo "Generated: $DATE_TAG $TIME_TAG"
    echo
    echo "## Summary"
    echo
    echo "- Gates passed: $PASS_COUNT/${#CHECK_IDS[@]}"
    echo "- Gates failed: $FAIL_COUNT/${#CHECK_IDS[@]}"
    echo "- Aggregate issue count: $TOTAL_ISSUES"
    echo "- Gate pass score: $QUALITY_SCORE"
    echo
    echo "## Check Results"
    echo
    echo "| Check | Status | Exit Code | Issues | Log |"
    echo "|---|---|---|---|---|"

    for i in "${!CHECK_IDS[@]}"; do
        echo "| ${CHECK_NAMES[$i]} | ${RESULT_STATUS[$i]} | ${RESULT_EXIT[$i]} | ${RESULT_ISSUES[$i]} | ${RESULT_LOG_REL[$i]} |"
    done

    echo
    echo "## First Signal Per Check"
    echo
    for i in "${!CHECK_IDS[@]}"; do
        echo "- ${CHECK_NAMES[$i]}: ${RESULT_SIGNAL[$i]}"
    done
    echo
    echo "## Notes"
    echo
    echo "- This report is generated by scripts/run_premium_baseline.sh."
    echo "- Use this report as the source of truth for tracker updates and sprint planning."
} > "$REPORT_FILE"

echo ""
echo "Baseline report generated: $REPORT_FILE"
echo ""

if [[ "$FAIL_COUNT" -gt 0 ]]; then
    exit 1
fi

exit 0
