// ==========================================================================
// FlxOS Config.hpp — AUTO-GENERATED by profile.cmake
// Profile: esp32s3-ili9341-xpt
// DO NOT EDIT — regenerated on every CMake configure from profile.yaml
// ==========================================================================
#pragma once

#include <driver/spi_master.h>

// ── Preprocessor feature flags (for #if guards only) ──
#define FLXOS_SD_CARD_ENABLED 1
#define FLXOS_BATTERY_ENABLED 0
#define FLXOS_HEADLESS 0

namespace flx::config {

// ── Struct Definitions ──

struct Profile {
    const char* id;
    const char* vendor;
    const char* boardName;
    const char* target;
};

struct DisplayConfig {
    bool enabled;
    const char* driver;
    int width, height, rotation, colorDepth;
    float sizeInches;
    struct { spi_host_device_t host; int mode, freqWrite, freqRead; bool threeWire; int dmaChannel; } spi;
    struct { int cs, dc, rst, busy, bckl, mosi, sclk, miso; } pins;
    struct { int offsetX, offsetY, offsetRotation, dummyReadPixel, dummyReadBits;
             bool readable, busShared, invert, rgbOrder, dlen16bit; } panel;
    struct { int freq, pwmChannel; bool invert; } backlight;
};

struct TouchConfig {
    bool enabled;
    const char* driver;
    struct { int cs, interrupt, sclk, mosi, miso; } pins;
    struct { int freq; bool busShared, separatePins; spi_host_device_t host; } spi;
    struct { int xMin, xMax, yMin, yMax, offsetRotation; } calibration;
};

struct SdCardConfig {
    bool enabled;
    int cs;
    spi_host_device_t spiHost;
    int maxFreqKhz;
    const char* mountPoint;
    struct { int mosi, miso, sclk; } pins;
};

struct BatteryConfig {
    bool enabled;
    int adcUnit, adcChannel;
    int voltageMax, voltageMin;
    int dividerFactor;
};

struct UsbConfig {
    bool tinyUsb;
};

struct CliConfig {
    bool enabled;
    const char* prompt;
    int maxCmdlineLength;
};

struct Capabilities {
    bool wifi, bluetooth, ble, gps, lora, camera, audio, keyboard, trackball;
};

// ── Compile-time constants (auto-generated from profile.yaml) ──

inline constexpr Profile profile {
    .id = "esp32s3-ili9341-xpt",
    .vendor = "FlxOS",
    .boardName = "ESP32-S3-ILI9341",
    .target = "esp32s3",
};

inline constexpr DisplayConfig display {
    .enabled = true,
    .driver = "ILI9341",
    .width = 240, .height = 320, .rotation = 1, .colorDepth = 16,
    .sizeInches = 2.8f,
    .spi = { .host = SPI2_HOST, .mode = 0, .freqWrite = 40000000, .freqRead = 16000000,
             .threeWire = false, .dmaChannel = 0 },
    .pins = { .cs = 10, .dc = 9, .rst = 14, .busy = -1, .bckl = 7,
              .mosi = 11, .sclk = 12, .miso = 13 },
    .panel = { .offsetX = 0, .offsetY = 0, .offsetRotation = 0,
               .dummyReadPixel = 8, .dummyReadBits = 1,
               .readable = true, .busShared = true, .invert = false,
               .rgbOrder = false, .dlen16bit = false },
    .backlight = { .freq = 20000, .pwmChannel = 0, .invert = false },
};

inline constexpr TouchConfig touch {
    .enabled = true,
    .driver = "XPT2046",
    .pins = { .cs = 5, .interrupt = 6, .sclk = -1, .mosi = -1, .miso = -1 },
    .spi = { .freq = 1000000, .busShared = true, .separatePins = false, .host = static_cast<spi_host_device_t>(-1) },
    .calibration = { .xMin = 3800, .xMax = 200, .yMin = 200, .yMax = 3800, .offsetRotation = 0 },
};

inline constexpr SdCardConfig sdcard {
    .enabled = true, .cs = 4, .spiHost = SPI2_HOST, .maxFreqKhz = 20000,
    .mountPoint = "/sdcard", .pins = { .mosi = -1, .miso = -1, .sclk = -1 },
};

inline constexpr BatteryConfig battery {
    .enabled = false,
    .adcUnit = 1, .adcChannel = 0,
    .voltageMax = 4200, .voltageMin = 3300,
    .dividerFactor = 200,
};

inline constexpr UsbConfig usb { .tinyUsb = false };

inline constexpr CliConfig cli {
    .enabled = true,
    .prompt = "flxos> ",
    .maxCmdlineLength = 256,
};

inline constexpr bool headless = false;

inline constexpr Capabilities capabilities {
    .wifi = true, .bluetooth = true, .ble = true,
    .gps = false, .lora = false, .camera = false,
    .audio = false, .keyboard = false, .trackball = false,
};

}  // namespace flx::config
